### ISSUE TITLE
Software likely contains a backdoor

### ISSUE THREAD

**Issue by cobaltjacket** [dverite/cryptint#1]
This package includes the Skipjack cipher, which [likely includes a 25 year-old backdoor](https://en.wikipedia.org/wiki/Skipjack_(cipher)).

**Comment by dverite** [comment]
The README has this warning already: "Be warned that this encryption algorithm was developed in the 80's and is considered extremely weak by today's standard", in addition to the link to Wikipedia.
I assume this warning is enough not to mistake this for crypto-grade stuff.
