### ISSUE TITLE
Transcodding XTEA to java

### ISSUE THREAD

**Issue by tdenat** [dverite/cryptint#2]
Hi,
I am trying to use an implementation of XTEA in java and i have some problems doing so. The java XTEA code that i use can encrypt any data and decrypt them correctly but the crypted value is different from what is obtained with the code in C. Our data are currently crypted with your script in C and we would like to avoid modifying the already crypted data. I have tried to rewrite your code in java but it looks like a source of this problem could be that the code in C uses unsigned integers that do not exist in java. Do you have any idea that could help me with this topic?
Thanks
Tom
https://github.com/mic-kul/jots/blob/master/src/main/java/jots/net/XTEA.java

**Comment by dverite** [comment]
Indeed the C code relies on modulo 2^32 arithmetic. I don't do Java myself, but I think that it would work to apply `value=value&0xffffffff` to the results of additions and subtractions involved (the 3 additions in the encryption loop and 3 substractions in the decryption loop)

**Comment by tdenat** [comment]
Oups je viens de voir que vous êtes français tout comme moi. Je vais tester votre méthode. Merci du coup de pouce.
