### ISSUE TITLE
Version 1.0.1 fails to install

### ISSUE THREAD

**Issue by anmolitor** [dverite/cryptint#4]
Due to the updated version, make install seems to look for a 1.0.1 file which it cannot find

`4.351 /usr/bin/install -c -m 644 .//sql/cryptint--1.0.1.sql  '/usr/local/share/postgresql/extension/'`

I was able to fix the error locally by renaming the 1.0.0 script to 1.0.1.

**Comment by dverite** [comment]
Thanks for pointing this out!
I've fixed this in the Makefile with commit 2a06bbf

**Comment by anmolitor** [comment]
Thanks!
